#    - name: Update and upgrade apt packages
#      become: true
#      apt:
#        upgrade: yes
#        update_cache: yes
#        cache_valid_time: 86400 #One day

#    - name: downlaod GPG key
#      get_url:
#        url:  https://pkg.jenkins.io/debian/jenkins.io.key
#        dest: /tmp/jenkins.io.key
---

- name: Adding Jenkins user
  user: name=jenkins groups=sudo,shadow shell=/bin/bash append=yes generate_ssh_key=yes ssh_key_file=.ssh/id_rsa

- name: Adding Jenkins user to sudoers
  lineinfile: dest=/etc/sudoers state=present regexp='^%jenkins' line='%jenkins ALL=(ALL) NOPASSWD:ALL' validate='visudo -cf %s'

- name: install apt-key
  apt_key:
    url:  https://pkg.jenkins.io/debian/jenkins.io.key
    state: present

# Manual installation
#   350  sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
#  351  add-apt-repository universe
#  352  add-apt-repository --help
#  353  add-apt-repository -y universe
#  354  apt-get update

- name: Add the Jenkins APT repository
  apt_repository: repo="deb http://pkg.jenkins-ci.org/debian binary/" state=present

- name: Install Jenkins
  apt: name={{item}} state=latest
  with_items:
  - jenkins

- name: Set HTTPS port
  lineinfile:
    dest:  '/etc/default/jenkins'
    insertafter: 'HTTP_PORT=8080'
    line: "HTTPS_PORT=8443"

- name: Jenkins args
  lineinfile:
     dest:  '/etc/default/jenkins'
     regexp: "JENKINS_ARGS"
     line: 'JENKINS_ARGS="--webroot=/var/cache/$NAME/war --httpPort=-1 --httpsPort=$HTTPS_PORT"'

- name: restart jenkins
  service: name=jenkins state=restarted

